version: '3.8'

services:
  # Backend service
  backend:
    image: server-textractify:latest
    build:
      context: ./server
    ports:
      - "3000:3000"

  # Client service
  client:
    image: client-textractify:latest
    build:
      context: ./client
    ports:
      - "80:80"
  
  # Client Textractify service
  textractify-client:
    image: client-textractify-client:latest
    build:
      context: ./textractify-client
    ports:
      - "81:81"

networks:
  default:
    name: textractify-network