name: client-build-push
on:
  push:
    paths:
    - 'client/**'

    branches:
      - master 
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:                       
      - uses: actions/checkout@v2                  
      - name: Login to Dockerhub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
            docker login -u $username -p $password 

      - name: Docker Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: frnn4268/client-textractify:${{github.run_number}}